# Generated by Django 5.2.2 on 2025-06-19 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=16)),
                ('expire_month', models.CharField(max_length=2)),
                ('expire_year', models.CharField(max_length=2)),
                ('cvv2', models.CharField(max_length=3)),
                ('credit_cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
