# Generated by Django 5.2.2 on 2025-06-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='credit_cards',
            new_name='user',
        ),
    ]
