# Generated by Django 5.2.2 on 2025-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_creditcard_expire_year_alter_creditcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
